### ISSUE TITLE
No Sberbank on iOS

### ISSUE THREAD

**Issue by justjew** [MrOlolo/sbp_payments#1]
On iOS devices there is no Sberbank option in `showBanks` modal.
On Android it works as expected.

**Comment by MrOlolo** [comment]
Maybe problem with iOS 15 entries limit in lists.
Watch `LSApplicationQueriesSchemes` key into you project `info.plist`

More information here (at Quick Start) -  https://github.com/MrOlolo/SBPPaymentsIOS

**Comment by justjew** [comment]
Oh, I didn't see this warning
`Warning! Starting with iOS 15 there's limit in maximum 50 entries in list, so you probably need to take first 50 entries from [c2bmembers.json](https://qr.nspk.ru/proxyapp/c2bmembers.json). Look for details [here](https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl#discussion).`

Thank you. I will try it.
